### ISSUE TITLE
Document gHRV support

### ISSUE THREAD

**Issue by mncharity** [oroce/polar-h7-rr#3]
Kubios download is regrettably behind a registration barrier.  An open-source alternative is [gHRV](http://milegroup.github.io/ghrv/) ([github](https://github.com/milegroup/ghrv)).

Usage:

1. Create an RR text file by trimming the polar-h7-rr csv: `cut -f2 < my-data.csv > my-data.txt`
2. Load  it into ghrv, using the UI (or using the command line: `python gHRV.py -loadBeatTXT somepath/my-data.txt`).

**Comment by oroce** [comment]
Hey @mncharity I added option for setting what `columns` should be included in the csv. I updated the readme. You dont need to use `cut` command anymore.

Also can i ask what are you using this small module for?
